# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Book.create([
    {title: "The Power of Meaning" , author: "Emily Esfahani Smith", img_url: "https://images.gr-assets.com/books/1465653308l/30008950.jpg", description: "This wise, stirring book argues that the search for meaning can immeasurably deepen our lives and is far more fulfilling than the pursuit of personal happiness."}, 
    {title: "Designing Your Life" , author: "Bill Burnett, Dave Evans", img_url: "https://images.gr-assets.com/books/1476133952l/26046333.jpg", description: "Whether we’re 20, 40, 60 or older, many of us are still looking for an answer to that perennial question, ‘What do you want to be when you grow up?’ In Designing Your Life, Silicon Valley design innovators Bill Burnett and Dave Evans use their expertise to help you work out what you want – and how to get it."}, 
    {title: "The Arabian Nights" , author: "Wafa' Tarnowska", img_url: "https://images.gr-assets.com/books/1347497895l/7959757.jpg", description: "Lebanese author Wafa' Tarnowska opens a window onto the Arab world with her magnificent new translation of eight stories from A Thousand and One Nights. This edition is notable for combining favourites such as 'Aladdin and the Wonderful Lamp' with less familiar tales such as 'The Diamond Anklet' and 'The Speaking Bird and the Singing Tree'. "}, 
    {title: "Homo Deus", author: "Yuval Noah Harari", img_url: "https://images.gr-assets.com/books/1455858241l/28092870.jpg", description: "Humans today enjoy unprecedented levels of power and an increasingly god-like status. The great epidemics of the past – famine, plague and war – no longer control our lives. We are the only species in history that has single-handedly changed the entire planet, and we can no longer blame a higher being for our fate."},
    {title: "The Last Lecture", author: "Randy Pausch", img_url: "https://images.gr-assets.com/books/1529682044l/40611510.jpg", description: "Based on the extraordinary final lecture by Carnegie Mellon University professor Randy Pausch, given after he discovered he had pancreatic cancer, this moving book goes beyond the now-famous lecture to inspire readers to live each day with purpose and joy."},
    {title: "Man's Search for Meaning", author: "Viktor E. Frankl", img_url: "https://images.gr-assets.com/books/1535419394l/4069.jpg", description: "Psychiatrist Viktor Frankl's memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival. Based on his own experience and the stories of his patients, Frankl argues that we cannot avoid suffering but we can choose how to cope with it, find meaning in it, and move forward with renewed purpose."},
    {title: "Wild", author: "Cheryl Strayed", img_url: "https://images.gr-assets.com/books/1453189881l/12262741.jpg", description: "At twenty-two, Cheryl Strayed thought she had lost everything. In the wake of her mother’s death, her family scattered and her own marriage was soon destroyed. Four years later, with nothing more to lose, she made the most impulsive decision of her life."},
    {title: "I Contain Multitudes", author: "Ed Yong", img_url: "https://images.gr-assets.com/books/1445606162l/27213168.jpg", description: "Joining the ranks of popular science classics like The Botany of Desire and The Selfish Gene, a groundbreaking, wondrously informative, and vastly entertaining examination of the most significant revolution in biology since Darwin—a “microbe’s-eye view” of the world that reveals a marvelous, radically reconceived picture of life on earth."},
    {title: "How to Read a Book", author: "Mortimer J. Adler,  Charles Van Doren", img_url: "https://images.gr-assets.com/books/1310993739l/567610.jpg", description: "How to Read a Book, originally published in 1940, has become a rare phenomenon, a living classic. It is the best and most successful guide to reading comprehension for the general reader. And now it has been completely rewritten and updated."},
    {title: "Books for Living", author: "Will Schwalbe", img_url: "https://images.gr-assets.com/books/1482427338l/30211956.jpg", description: "From the author of the best-selling and beloved The End of Your Life Book Club - a wonderfully engaging new book: both a celebration of reading in general and an impassioned recommendation of specific books that can help guide us through our daily lives."},
])
